# Every invocation is help, dry-run, or rejected before device enumeration.
function(expect code pattern)
  execute_process(COMMAND "${TOOL}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
  if(NOT result STREQUAL "${code}")
    message(FATAL_ERROR "${ARGN}: exit ${result}, expected ${code}\n${output}\n${error}")
  endif()
  if(NOT "${output}${error}" MATCHES "${pattern}")
    message(FATAL_ERROR "${ARGN}: missing expected pattern '${pattern}'\n${output}\n${error}")
  endif()
endfunction()

expect(0 "Windows HID userspace prototype" --help)
expect(0 "00 F8 81 84 03 00 00 00" range 900 --dry-run)
expect(0 "00 F8 81 1C 02 00 00 00" range 540 --dry-run)
expect(0 "00 F8 10 00 00 00 00 00" native --dry-run)
expect(0 "00 11 00 A6 00 00 00 00" test-ffb --dry-run)
expect(0 "00 21 0B 80 80 EE 00 4C" center --dry-run)
expect(0 "00 41 0C 0F 00 0F 00 4C" test-ffb damper --dry-run)
expect(0 "00 F3 00 00 00 00 00 00" stop --dry-run)
expect(2 "range must be" range 901 --dry-run)
expect(2 "range must be" range -1 --dry-run)
expect(2 "invalid integer" range 900junk --dry-run)
expect(2 "range requires" range)
expect(2 "effect must be" test-ffb maximum --dry-run)
expect(2 "unknown DirectInput effect" directinput-test maximum)
expect(2 "unexpected option" test-ffb --force 100 --dry-run)
expect(2 "unexpected option" monitor --dry-run)
expect(2 "seconds must be" monitor --seconds 0)
expect(2 "nonnegative" info --device -1)
expect(2 "unknown command" garbage)
message(STATUS "19 CLI dry-run/argument checks passed; no hardware I/O")
