// SPDX-License-Identifier: GPL-2.0-only
#include "protocol/logitech_protocol.h"
#include "protocol/force_feedback.h"
#include "device/output_session.h"
#include <cmath>
#include <iostream>
#include <stdexcept>
#include <vector>

namespace {
int checks = 0;
void check(bool value, const char* name) {
    ++checks;
    if (!value) throw std::runtime_error(name);
}
template<class F> void rejects(F&& fn, const char* name) {
    bool caught = false;
    try { fn(); } catch (const std::exception&) { caught = true; }
    check(caught, name);
}
struct FakeWriter : g25::ReportWriter {
    std::vector<g25::Command> writes;
    int fail_on = -1;
    void send(const g25::Command& command) override {
        writes.push_back(command);
        if (static_cast<int>(writes.size()) == fail_on) throw std::runtime_error("injected write failure");
    }
};
void run() {
    using namespace g25;
    check(set_range(900) == Command{0xf8, 0x81, 0x84, 3, 0, 0, 0}, "900 golden vector");
    check(set_range(540) == Command{0xf8, 0x81, 0x1c, 2, 0, 0, 0}, "540 golden vector");
    check(set_range(40)[2] == 40, "range lower bound");
    rejects([] { (void)set_range(39); }, "reject small range");
    rejects([] { (void)set_range(901); }, "reject large range");
    check(windows_output(native_mode()) == WindowsOutput{0, 0xf8, 0x10, 0, 0, 0, 0, 0}, "Windows report ID");
    check(identify_model(dfex_pid, 0x1222) == Model::g25, "compatibility G25");
    check(identify_model(g25_pid, 0x1230) == Model::g27, "exclude G27 masquerading as G25");
    check(identify_model(dfp_pid, 0x1352) == Model::g29, "exclude G29");
    check(identify_model(dfex_pid, 0x2100) == Model::unknown, "exclude Formula EX");
    check(identify_model(0xffff, 0x1222) == Model::unknown, "unknown PID");
    check(identify_model(g27_pid, 0x1222) == Model::unknown, "G25 cannot have native G27 PID");

    // Hand-assembled bit-boundary vector (not generated by the decoder).
    const std::array<std::uint8_t, 12> report{0, 0x98, 0x01, 0x80, 0x02, 0x80, 0xff, 0, 0x7f, 0x12, 0x34, 0x56};
    const auto state = decode_windows_input(report);
    check(state.wheel == 8192 && state.buttons == 0x19 && state.hat == 8, "unaligned axes/buttons");
    check(state.vendor_bits == 5, "vendor bits must not become buttons");
    check(state.vendor_bytes == std::array<std::uint8_t, 3>{0x12, 0x34, 0x56}, "preserve opaque vendor bytes");
    check(state.throttle == 255 && state.brake == 0 && state.clutch == 127, "independent pedals");
    check(InputState::pedal_percent(255) == 0 && InputState::pedal_percent(0) == 100, "pedal endpoints");
    check(std::abs(state.angle(900)) < 0.03, "center quantization");
    InputState endpoint; endpoint.wheel = 0;
    check(endpoint.angle(540) == -270, "left range conversion");
    endpoint.wheel = 16383;
    check(endpoint.angle(900) == 450, "right range conversion");
    for (unsigned bit = 0; bit < 19; ++bit) {
        std::array<std::uint8_t, 11> payload{};
        const unsigned offset = bit + 4;
        payload[offset / 8] = static_cast<std::uint8_t>(1u << (offset % 8));
        check(decode_native_payload(payload).buttons == (1u << bit), "each HID button survives");
    }
    for (unsigned bit = 0; bit < 7; ++bit) {
        InputState gear; gear.buttons = 1u << (bit + 8);
        check(gear.indicated_gear() == (bit == 6 ? "R" : std::to_string(bit + 1)), "gear interpretation");
    }
    InputState gear; gear.buttons = 3u << 8;
    check(gear.indicated_gear() == "?", "ambiguous gear");
    gear.buttons = 0; check(gear.indicated_gear() == "N", "neutral gear");
    rejects([&] { (void)decode_windows_input(std::span(report).first(11)); }, "short Windows report");
    auto bad = report; bad[0] = 1;
    rejects([&] { (void)decode_windows_input(bad); }, "unknown report ID");
    rejects([&] { (void)decode_native_payload(report); }, "reject Windows frame as USB payload");

    check(constant_force(0)[2] == 0x80, "force neutral is 0x80");
    check(constant_force(-32768)[2] == 0 && constant_force(32767)[2] == 255, "signed force endpoints");
    check(constant_force(-1024)[2] == 0x7c, "negative force");
    check(low_force_test(TestEffect::constant) == Command{0x11, 0, 0xa6, 0, 0, 0, 0}, "bounded constant vector");
    check(low_force_test(TestEffect::spring) == Command{0x21, 0x0b, 0x80, 0x80, 0xee, 0, 0x4c}, "bounded spring vector");
    check(low_force_test(TestEffect::damper) == Command{0x41, 0x0c, 15, 0, 15, 0, 0x4c}, "bounded damper vector");
    check(spring(0, 0, 0, 0, 256) == Command{0x21, 0x0b, 0, 0xff, 0, 0xe0, 1}, "spring zero coefficient boundaries");
    check(damper(-32768, -4096, 65535) == Command{0x41, 0x0c, 15, 1, 2, 1, 255}, "signed damper saturation");
    check(friction(-32768, 4096, 65535) == Command{0x81, 0x0e, 255, 32, 255, 1, 0}, "signed friction saturation");
    check(spring(0, 0, 8192, 8192, 0)[0] == 0x23, "zero clip stops spring");
    check(damper(4096, 4096, 0)[0] == 0x43, "zero clip stops damper");
    check(stop_force_slot(0) == Command{0x13, 0, 0, 0, 0, 0, 0}, "stop constant slot");
    check(stop_force_slot(1)[0] == 0x23 && stop_force_slot(2)[0] == 0x43 &&
          stop_force_slot(3)[0] == 0x83, "stop condition slots");
    rejects([] { (void)stop_force_slot(4); }, "reject invalid force slot");
    rejects([] { (void)spring(1, -1, 1, 1, 1); }, "invalid spring deadband");

    FakeWriter normal;
    { OutputSession session(normal); session.initialize(); normal.send(low_force_test(TestEffect::constant)); session.finish(); }
    check(normal.writes.size() == 5 && normal.writes[3] == stop_all() && normal.writes[4] == disable_autocenter(), "normal cleanup order");
    for (int failure = 1; failure <= 5; ++failure) {
        FakeWriter writer; writer.fail_on = failure;
        try {
            OutputSession session(writer);
            session.initialize(); writer.send(low_force_test(TestEffect::constant)); session.finish();
        } catch (const std::exception&) {}
        check(writer.writes[writer.writes.size() - 2] == stop_all() && writer.writes.back() == disable_autocenter(), "cleanup after every possible write failure");
    }
    FakeWriter interrupted;
    { OutputSession session(interrupted); session.initialize(); interrupted.send(low_force_test(TestEffect::spring)); }
    check(interrupted.writes[3] == stop_all() && interrupted.writes[4] == disable_autocenter(), "early return cleanup");
}
}
int main() {
    try { run(); std::cout << checks << " protocol/safety checks passed (no hardware I/O)\n"; return 0; }
    catch (const std::exception& error) { std::cerr << "FAIL: " << error.what() << '\n'; return 1; }
}
